# Generated by Django 5.2.4 on 2026-08-09 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailsEmaildata",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("latitude", models.CharField(max_length=50)),
                ("longitude", models.CharField(max_length=50)),
                ("city", models.CharField(max_length=100)),
                ("address", models.TextField()),
                ("image_time", models.DateTimeField()),
                (
                    "image_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("image_url", models.CharField(max_length=255)),
                ("image_file", models.CharField(blank=True, max_length=255, null=True)),
                ("status", models.CharField(max_length=50)),
                ("typo", models.CharField(max_length=20)),
                ("status_int", models.IntegerField(blank=True, null=True)),
                ("quartiere", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "emails_emaildata",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="FreeWeb",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.CharField(blank=True, max_length=50, null=True)),
                ("longitude", models.CharField(blank=True, max_length=50, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("image_time", models.DateTimeField(blank=True, null=True)),
                ("image_id", models.CharField(blank=True, max_length=255, null=True)),
                ("image_url", models.CharField(blank=True, max_length=200, null=True)),
                ("image_file", models.CharField(blank=True, max_length=100, null=True)),
                ("status", models.CharField(max_length=50)),
                ("typo", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "free_web",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Trees",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lat", models.FloatField(blank=True, null=True)),
                ("lon", models.FloatField(blank=True, null=True)),
                ("info", models.CharField(blank=True, null=True)),
            ],
            options={
                "db_table": "trees",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(blank=True, null=True)),
                ("hashed_password", models.CharField(blank=True, null=True)),
                ("api_key", models.CharField(blank=True, null=True)),
                ("can_regenerate_key", models.CharField(blank=True, null=True)),
                ("api_key_creation_date", models.DateTimeField(blank=True, null=True)),
                ("email", models.CharField(blank=True, null=True, unique=True)),
                ("is_active", models.BooleanField(blank=True, null=True)),
                (
                    "facebook_id",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("name", models.CharField(blank=True, null=True)),
                (
                    "google_id",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("avatar_url", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "users",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UserRateLimit",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="rifiuti.users",
                    ),
                ),
                ("count", models.IntegerField(blank=True, null=True)),
                ("is_banned", models.BooleanField(blank=True, null=True)),
                ("ban_reason", models.TextField(blank=True, null=True)),
                ("banned_until", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("sent", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "user_rate_limit",
                "managed": False,
            },
        ),
    ]
