# Generated by Django 5.2.4 on 2026-08-09 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("is_superuser", models.BooleanField()),
                ("username", models.CharField(max_length=150, unique=True)),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                ("email", models.CharField(max_length=254)),
                ("is_staff", models.BooleanField()),
                ("is_active", models.BooleanField()),
                ("date_joined", models.DateTimeField()),
            ],
            options={
                "db_table": "auth_user",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="FreeWeb",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.CharField(blank=True, max_length=50, null=True)),
                ("longitude", models.CharField(blank=True, max_length=50, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("image_time", models.DateTimeField(blank=True, null=True)),
                ("image_id", models.CharField(blank=True, max_length=255, null=True)),
                ("image_url", models.CharField(blank=True, max_length=200, null=True)),
                ("image_file", models.CharField(blank=True, max_length=100, null=True)),
                ("status", models.CharField(max_length=50)),
                ("typo", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "free_web",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UserRateLimit",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="core.users",
                    ),
                ),
                ("count", models.IntegerField(blank=True, null=True)),
                ("is_banned", models.BooleanField(blank=True, null=True)),
                ("ban_reason", models.TextField(blank=True, null=True)),
                ("banned_until", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("sent", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "user_rate_limit",
                "managed": False,
            },
        ),
        migrations.DeleteModel(
            name="AlembicVersion",
        ),
        migrations.DeleteModel(
            name="ApiKeys",
        ),
        migrations.AlterModelOptions(
            name="emailsemaildata",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="trees",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="users",
            options={"managed": False},
        ),
    ]
