# Generated by Django 3.2.8 on 2025-03-01 21:32

import datetime
from django.db import migrations, models
import reportweb.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('image_time', models.DateTimeField(default=datetime.datetime.now)),
                ('image_id', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('image_file', models.ImageField(blank=True, null=True, upload_to=reportweb.models.get_image_path)),
                ('status', models.CharField(choices=[('pending', 'In attesa'), ('approved', 'Approvato'), ('rejected', 'Rifiutato')], default='pending', max_length=20)),
                ('typo', models.CharField(choices=[('web', 'Web'), ('email', 'Email'), ('app', 'Applicazione')], default='web', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
