# Generated by Django 3.2.8 on 2025-03-09 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='image_url',
        ),
    ]
