# Generated by Django 3.2.8 on 2025-03-09 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_remove_report_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
