# Generated by Django 3.2.8 on 2025-03-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_report_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='typo',
            field=models.CharField(choices=[('rifiuti', 'Rifiuti'), ('tronchi', 'Tronchi'), ('censimento', 'Censimento'), ('piantumazione', 'Piantumazione')], default='web', max_length=20),
        ),
    ]
