# Generated by Django 3.2.8 on 2025-03-09 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_alter_report_typo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
