# Generated by Django 3.2.8 on 2025-03-19 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_report_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='description',
            field=models.CharField(blank=True, help_text="Inserisci una breve descrizione dell'upload (max 200 caratteri).", max_length=200, null=True),
        ),
    ]
