# Generated by Django 3.2.8 on 2025-03-20 18:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('report', '0007_report_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='confirmations',
            field=models.ManyToManyField(blank=True, related_name='confirmed_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
