# Generated by Django 5.2.4 on 2025-07-27 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0008_report_confirmations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="image_file",
            field=models.ImageField(blank=True, null=True, upload_to="reports/"),
        ),
    ]
