# Generated by Django 5.2.4 on 2026-08-12 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0009_alter_report_image_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="typo",
            field=models.CharField(
                choices=[
                    ("rifiuti", "Rifiuti"),
                    ("tronchi", "Tronchi"),
                    ("censimento", "Censimento"),
                    ("piantumazione", "Piantumazione"),
                    ("strade", "Strade"),
                ],
                default="web",
                max_length=20,
            ),
        ),
    ]
