# Generated by Django 5.2.4 on 2026-08-13 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_authuser_freeweb_userratelimit_delete_alembicversion_and_more"),
        ("report", "0010_alter_report_typo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.users",
            ),
        ),
    ]
