# Generated by Django 5.2.4 on 2026-08-13 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_authuser_freeweb_userratelimit_delete_alembicversion_and_more"),
        ("report", "0011_alter_report_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="confirmations",
            field=models.ManyToManyField(
                blank=True, related_name="confirmed_reports", to="core.users"
            ),
        ),
    ]
