# Generated by Django 5.2.4 on 2026-08-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TesterRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=100, verbose_name="Nome Completo"),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="L'indirizzo email associato al tuo dispositivo Android.",
                        max_length=254,
                        unique=True,
                        verbose_name="Email Account Google / Play Store",
                    ),
                ),
                (
                    "agreed_to_terms",
                    models.BooleanField(
                        default=False,
                        verbose_name="Accetto di tenere l'app installata per almeno 14 giorni",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Iscrizione Tester",
                "verbose_name_plural": "Iscrizioni Tester",
                "ordering": ["-created_at"],
            },
        ),
    ]
