"""
Django settings for citylog project.

Generated by 'django-admin startproject' using Django 3.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-+@^slyn0z^or(6&0uuwxbqb)sje*wvsctd63gbah0biy$+)&a5'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Switch from sqlite3 and postgresql
SWITCH_DB = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'report',
    'utilities',
    'django_system_info',
    'django_users_accounts',
    'crispy_forms',
    'crispy_bootstrap4',
    'facebook_auth',

    'rifiuti',   # o 'rifiuti.apps.RifiutiConfig'
    'ambiente',  # o 'ambiente.apps.AmbienteConfig'
    'strade',  # o 'ambiente.apps.AmbienteConfig'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'citylog.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django_system_info.context_processors.system_info',
            ],
        },
    },
]

AUTHENTICATION_BACKENDS = (
    'social_core.backends.facebook.FacebookOAuth2',
    'django.contrib.auth.backends.ModelBackend',
    'facebook_auth.backends.FacebookAuthBackend',  # Backend personalizzato per Facebook
 )

WSGI_APPLICATION = 'citylog.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

if not SWITCH_DB:

     DATABASES = {
         'default': {
             'ENGINE': 'django.db.backends.sqlite3',
             'NAME': BASE_DIR / 'db.sqlite3',
         }
     }
else:

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': 'citylog',
            'USER': 'postgres',
            'PASSWORD': 'postgres123',
            'HOST': 'localhost',
            'PORT': '5432',
    },
        'segnalazioni_db': {  # Database delle segnalazioni (da importare)
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': 'geodumbmail_alembic',
            'USER': 'postgres',
            'PASSWORD': 'postgres123',
            'HOST': 'localhost',
            'PORT': '5432',
    }
}

DATABASE_ROUTERS = ['core.db_router.SegnalazioniRouter']


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static/')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# to send email
EMAIL_HOST = 'smtp.code4you.cloud'
EMAIL_HOST_USER = 'info@citylog.cloud'
EMAIL_HOST_PASSWORD = 'Blacking1'
FROM_EMAIL = 'noreply@citylof.cloud'
SERVER_EMAIL = 'noreply@citylog.cloud'
EMAIL_PORT = 587
EMAIL_USE_TLS = False

# django-facebook-auth
FACEBOOK_APP_ID = "1233024841238630"
FACEBOOK_APP_SECRET = "2e4014a04501a202e71b9a5679155de5"
FACEBOOK_REDIRECT_URI = "https://citylog.cloud/facebook/callback/"

SOCIAL_AUTH_REDIRECT_IS_HTTPS = True
#SECURE_SSL_REDIRECT = True
SOCIAL_AUTH_FACEBOOK_SCOPE = ['email']
#SOCIAL_AUTH_FACEBOOK_SCOPE = "email,public_profile"

SOCIAL_AUTH_FACEBOOK_PROFILE_EXTRA_PARAMS = {
    'fields': 'id, name, email'
}

# redirect to login facebook
#LOGIN_URL = '/'

# django-system-info
SYSTEM_INFO_ENABLED = True
import django
DJANGO_VERSION = django.get_version()

SYSTEM_INFO_TEMPLATE = "core/system_info.html"

# django-simple-accounts
CRISPY_TEMPLATE_PACK = 'bootstrap4'

LOGIN_URL = 'login'
LOGOUT_URL = 'logout'
LOGOUT_REDIRECT_URL ='login'
LOGIN_REDIRECT_URL ='profile'

# django-custom-storage
DEFAULT_FILE_STORAGE = "custom_storage.backends.CustomMediaStorage"

# django-custom-storage endpoint
REMOTE_STORAGE_UPLOAD_URL = 'https://ws.citylog.cloud/upload'
REMOTE_STORAGE_MEDIA_URL = 'https://ws.citylog.cloud/media'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'WARNING',  # O 'DEBUG' per più dettagli
            'class': 'logging.FileHandler',
            'filename': '/usr/share/citylog/logs/error.log',  # Percorso del file di log
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'WARNING',
            'propagate': True,
        },
    },
}
